---
kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - bin/compile
  volumes:
    - name: cache
      path: /drone/src/build

- name: deploy
  image: mesosphere/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  volumes:
    - name: cache
      path: /drone/src/build
  commands:
    - bin/deploy
  when:
    branch:
      - master

volumes:
  - name: cache
    temp: {}

trigger:
  branch:
    - master

---
kind: signature
hmac: 5e02c1304903bb3c59b2be97fb144269a3893efeaaf7a2cf140fea310928acfa
