---
kind: pipeline
name: default

steps:
- name: build
  image: ruby
  commands:
    - gem update bundler
    - bundle install --deployment
    - bundle exec middleman build --verbose
  volumes:
    - name: cache
      path: /drone/src/build

- name: deploy
  image: mesosphere/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  volumes:
    - name: cache
      path: /drone/src/build
  commands:
    - bin/deploy
  when:
    branch:
      - master

volumes:
  - name: cache
    temp: {}

trigger:
  branch:
    - master

---
kind: signature
hmac: 13fb19051fd60d2d9627784cce8d24413c0d17039cf141ca321a5809dfa87af6

...
